# Generated by Django 5.2.10 on 2026-02-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_historicalsociomodel_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrarmodel',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN_PROCESO_JUSTIFICACION', 'EN_PROCESO_JUSTIFICACION'), ('PAGADA_PARCIALMENTE', 'PAGADA_PARCIALMENTE'), ('FACTURADO', 'FACTURADO'), ('PAGADA', 'PAGADA'), ('ANULADO', 'ANULADO')], default='PENDIENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcuentaporcobrarmodel',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN_PROCESO_JUSTIFICACION', 'EN_PROCESO_JUSTIFICACION'), ('PAGADA_PARCIALMENTE', 'PAGADA_PARCIALMENTE'), ('FACTURADO', 'FACTURADO'), ('PAGADA', 'PAGADA'), ('ANULADO', 'ANULADO')], default='PENDIENTE', max_length=50),
        ),
    ]
