# Generated by Django 5.2.10 on 2026-02-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_estados_duales_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfacturamodel',
            name='estado',
        ),
        migrations.AddField(
            model_name='historicalfacturamodel',
            name='estado_financiero',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='facturamodel',
            name='estado_sri',
            field=models.CharField(choices=[('NO_ENVIADA', 'No Enviada'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('PENDIENTE_SRI', 'Pendiente en SRI'), ('AUTORIZADA', 'Autorizada'), ('DEVUELTA', 'Devuelta'), ('RECHAZADA', 'Rechazada'), ('ERROR', 'Error')], default='NO_ENVIADA', help_text='Estado devuelto por el SRI (RECIBIDA, AUTORIZADO, etc)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalfacturamodel',
            name='estado_sri',
            field=models.CharField(choices=[('NO_ENVIADA', 'No Enviada'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('PENDIENTE_SRI', 'Pendiente en SRI'), ('AUTORIZADA', 'Autorizada'), ('DEVUELTA', 'Devuelta'), ('RECHAZADA', 'Rechazada'), ('ERROR', 'Error')], default='NO_ENVIADA', help_text='Estado devuelto por el SRI (RECIBIDA, AUTORIZADO, etc)', max_length=50),
        ),
    ]
